version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: locodb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: <Your-Password>
      POSTGRES_DB: locodb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./SQL:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped
  postgrest:
    image: postgrest/postgrest:latest
    container_name: locoapi
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://admin:<Your-Password>@db:5432/locodb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db_data: null
networks: {}
